use_frameworks!

platform :ios, '9.0'

target 'JLRoutesExtension_Example' do
  pod 'JLRoutesExtension', :path => '../'

  target 'JLRoutesExtension_Tests' do
    inherit! :search_paths

    
  end
end
